language: cpp

jobs:
  include:
    - os: linux
      dist: precise
      addons:
        apt:
          update: true
          packages:
            - doxygen
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo add-apt-repository -y ppa:fkrull/deadsnakes
        - sudo apt-add-repository 'deb https://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
        # Workaround: https://github.com/skyportal/skyportal/commit/6e639e4b4af93323095b22bb3994ccc358a4b379
        - sudo rm -f /etc/apt/sources.list.d/mongodb*
        - sudo rm -f /etc/apt/sources.list.d/couchdb*
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
        - sudo apt-get -q update
        - sudo apt-get -y install clang-4.0 clang++-4.0 python3.5 python3.5-dev
        - wget https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-Linux-x86_64.sh
        - sudo sh cmake-3.18.1-Linux-x86_64.sh --prefix=/usr --skip-license
        - wget -q -O - https://bootstrap.pypa.io/get-pip.py | sudo python3.5
        - export CC=clang-4.0
        - export CXX=clang++-4.0
        - if [[ -z "$(ls -A ${TRAVIS_BUILD_DIR}/deps)" ]]; then bash ${TRAVIS_BUILD_DIR}/deps.sh; fi
    - os: osx
      addons:
        homebrew:
          packages:
            - binutils
            - sphinx-doc
            - texinfo
            - python3
            - doxygen
            - cmake
            - wget
          update: true
      before_install:
        - export CC=clang
        - export CXX=clang++
        - if [[ -z "$(ls -A ${TRAVIS_BUILD_DIR}/deps)" ]]; then bash ${TRAVIS_BUILD_DIR}/deps.sh; fi
        - brew link --overwrite python3
      install:
        - python3 -m pip install --upgrade pip
        - python3 -m pip install wheel sphinx sphinx-rtd-theme breathe exhale

before_script:
  - export PYTHONPATH="${TRAVIS_BUILD_DIR}/test/python"
  - export SEQ_PATH="${TRAVIS_BUILD_DIR}/stdlib"
  - export LDFLAGS="-L/usr/local/lib"
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/deps/lib:$LD_LIBRARY_PATH
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export SEQ_PYTHON=$(python3.5 test/python/find-python-library.py)
      export LIBEXT="so"
      sudo ldconfig
    else
      export SEQ_PYTHON=$(python3 test/python/find-python-library.py)
      export LIBEXT="dylib"
    fi
    echo ${SEQ_PYTHON}

script:
  - mkdir build
  - |
    (cd build && cmake .. -DCMAKE_BUILD_TYPE=Release \
                          -DSEQ_DEP=${TRAVIS_BUILD_DIR}/deps \
                          -DCMAKE_C_COMPILER=${CC} \
                          -DCMAKE_CXX_COMPILER=${CXX})
  - ln -s ${TRAVIS_BUILD_DIR}/deps/lib/libomp.${LIBEXT} build/libomp.${LIBEXT}
  - cmake --build build --config Release -- VERBOSE=1
  - build/seqtest
  - build/seqc test/core/helloworld.seq
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      if ! make -C docs/sphinx html 2>sphinx.log ; then
        cat sphinx.log
        false
      fi
    fi
  - export SEQ_BUILD_ARCHIVE=seq-`uname -s | awk '{print tolower($0)}'`-`uname -m`.tar.gz
  - export SEQ_DEP_ARCHIVE=seq-deps-${TRAVIS_OS_NAME}.tar.bz2
  - |
    cat > bintray.json << EOD
    {
      "package": {
        "name": "seq",
        "repo": "seq",
        "subject": "seq-lang",
        "vcs_url": "https://github.com/seq-lang/seq",
        "licenses": ["Apache 2.0"]
      },
      "version": {
        "name": "develop"
      },
      "files": [
        {
          "includePattern": "${SEQ_BUILD_ARCHIVE}",
          "uploadPattern": "${TRAVIS_OS_NAME}/${SEQ_BUILD_ARCHIVE}",
          "matrixParams": { "override": 1 }
        },
        {
          "includePattern": "${SEQ_DEP_ARCHIVE}",
          "uploadPattern": "${TRAVIS_OS_NAME}/${SEQ_DEP_ARCHIVE}",
          "matrixParams": { "override": 1 }
        }
      ],
      "publish": true
    }
    EOD


before_deploy:
  - mkdir -p seq-deploy/bin seq-deploy/lib/seq
  - cp build/seqc seq-deploy/bin/
  - cp build/libseq*.${LIBEXT} seq-deploy/lib/seq/
  - cp deps/lib/libomp.${LIBEXT} seq-deploy/lib/seq/
  - cp -r stdlib seq-deploy/lib/seq/
  - tar -czf ${SEQ_BUILD_ARCHIVE} seq-deploy
  - tar -cjf ${SEQ_DEP_ARCHIVE} deps
  - du -sh seq-deploy
  - du -sh deps
  - ls -lah ${SEQ_DEP_ARCHIVE}

deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file:
      - ${SEQ_BUILD_ARCHIVE}
    skip_cleanup: true
    on:
      repo: seq-lang/seq
      tags: true
  - provider: pages
    local_dir: docs/sphinx/_build/html
    target_branch: gh-pages
    fqdn: seq-lang.org
    token: $GITHUB_TOKEN
    committer_from_gh: true
    keep_history: false
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = osx
  - provider: bintray
    user: inumanag
    key:
      secure: lGfhxQMpQhOk1UxYccjmRe8IcBIPpn66db92XOCPsELd6S2ZfyJSZgW0AQD51xf31k3s0wCbCn9USyB7oD8iIxGGKQgVB8BRvY+WS6ooO4DeUfXWhW0Hgw9yCrIXZTsO6QTz/DWiwrLYf4rn2vETezji9ou635uKYRB9Cq8gPWXd5QtZRn/YzwZnaOA+crKYcHDZC5Y6meXKPUW9DYvneheh2Tve4TTjc+YjykwAKrjIaaD/xmTcWS8kXBYFxdWsnORQprN3zNmqFNa/7nPHUG7/oI/rB/qdLxS1B3NPDVpLF8L6/OFV0ufqhQ9xLyRIJKegzKE7iLid2XMWKBJ6v5KN2GhVje5+EeKUWfYBuJfS/EDHeRpFf5T/cLpC1iy85X5tSqBV4x6OQsdfmW5gxiloeV76GUz4LErEUHQreZLk4eCDv3q8dGpV25hI7LHUzGvXdb7o6BZuxGGnz8JWhOKYl9fVc+ho2FxmW7Dr/dYik81o0Dmrg7gYM/q6SVdSTHWUg06nMy1LLvxS0TaiHR0Car8pgaQMglysw0PWuIN7+y7SV/X9z5bY7uQN92jcTvcfv0RpyZQ8a5J9TCQhIS+j36YiONz3UJ1R+m+QE3IyiY8Ws1rNUYTi7u6EUuW6/DVlsYhLW8EVslUgiFKJjG+YXACuF9N/XPYBCL+olWU=
    file: bintray.json
    skip_cleanup: true
    on: develop

cache:
  timeout: 1000
  directories:
    - deps

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bcb19a2bb1bab2a3b1b
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
  email: false
